### ISSUE TITLE
read only bind account request

### ISSUE THREAD

**Issue by JakeDEvans** [peterpakos/checkipaconsistency#43] opened 2018-01-24 16:31 UTC
Please provide instructions to create a read only account for doing these checks, `cn=Directory Manager` has FULL access, which is not necessary.

The example below does not have access to `cn=config`
```
# ldapmodify -x -D 'cn=Directory Manager' -W
dn: uid=system,cn=sysaccounts,cn=etc,dc=example,dc=com
changetype: add
objectclass: account
objectclass: simplesecurityobject
uid: system
userPassword: secret123
passwordExpirationTime: 20380119031407Z
nsIdleTimeout: 0
<blank line>
^D
```

Reference: https://www.freeipa.org/page/HowTo/LDAP#System_Accounts

**Comment by peterpakos** [comment] 2018-01-24 16:35
This seems like a duplicate of #30 and #32.

**Comment by JakeDEvans** [comment] 2018-01-24 16:39
Looks like your closed the issue as "Won't Fix" then?

**Comment by peterpakos** [comment] 2018-01-24 16:41
Yes. I'm open to suggestions if you have an idea on how to fix it though.

**Comment by JakeDEvans** [comment] 2018-01-24 16:45
I'm trying to parse through http://www.openldap.org/doc/admin24/access-control.html to figure it out.

**Comment by JensTimmerman** [comment] 2018-01-29 10:10
A user has been added to especially for reading replication data
see https://www.redhat.com/archives/freeipa-users/2013-August/msg00000.html
resulting in https://bugzilla.redhat.com/show_bug.cgi?id=1108215
fixed in https://pagure.io/freeipa/c/86f943ca180a72c4cfa3a8a03226f2471a97981b

So as far as I understand this, you should only need a user with the privilege `Replication Administrators` to check replication data.

This does not allow for enough permissions for this cipa script, but I imagine a similar issue could be created resulting in a role/privilege that could easily be used for end users?
Maybe something along the line of a "Directory Readers" privilege

```
kinit admin
ipa user-add --random cipa
ipa role-add cipa --desc "Check ipa consistency"
ipa role-add-privilege cipa --privileges 'Replication Administrators'
ipa role-add-member cipa --users cipa
```

**Comment by peterpakos** [comment] 2018-02-07 00:01
@JensTimmerman did you manage to create a role/account that satisfies all requirements/access rights of the script?

**Comment by peterpakos** [comment] 2018-02-28 19:29
Feel free to reopen this issue should you find a potential solution.

**Closed by peterpakos** 2018-02-28 19:29 UTC
Labels: enhancement

**Comment by fatmcgav** [comment] 2018-04-04 16:24
@JakeDEvans @JensTimmerman Did you ever find a workaround for using the DM account?

**Comment by JensTimmerman** [comment] 2018-04-05 10:43
No, I think someone ought to make a ticket bugzilla/pagure requesting a user with the correct permissions for exactly this purpose, as was done for the user to check replication data.

**Comment by stepan-vardanyan** [comment] 2023-05-09 15:23
Hey everyone.
I've found a way to run check with read-only user (in Prerequisites section specifically) and wrote next instruction for our company. The only issue is Ghost replicas test still doesn't work, couldn't pick appropriate permissions, but rest works fine. Hope you'll find it useful.
[README-cipa-readonly-user.md](https://github.com/peterpakos/checkipaconsistency/files/11432382/README-cipa-readonly-user.md).
cc @peterpakos
